### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by marcelowu** [develodesign/vsf-payment-paypal#101]
0.6 not finalize payment
![2019-08-16 00-30-42屏幕截图](https://user-images.githubusercontent.com/30912144/63141784-61ad9200-bfbd-11e9-96ce-9562571b5429.png)

**Comment by wubuyun** [comment]
Country=BR&locale.x=pt_BR ?

https://www.sandbox.paypal.com/checkoutnow?buttonSessionID=e5c33fbf77_mdq6mda6ndq&fundingSource=paypal&buyerCountry=BR&locale.x=pt_BR&commit=true&clientID=ARhAbf_ke3_T5F3J1bNXfIVMITf8UsJ8NqFIdEzbkeVMqEriqBnTTzVF9QO9osQlxWQTQi3cFkJhVIZF&sessionID=429e23ae9c_mdm6ndk6mde&env=sandbox&sdkMeta=eyJ1cmwiOiJodHRwczovL3d3dy5wYXlwYWwuY29tL3Nkay9qcz9jbGllbnQtaWQ9QVJoQWJmX2tlM19UNUYzSjFiTlhmSVZNSVRmOFVzSjhOcUZJZEV6YmtlVk1xRXJpcUJuVFR6VkY5UU85b3NRbHhXUVRRaTNjRmtKaFZJWkYiLCJzdGFnZUhvc3QiOm51bGwsImFwaVN0YWdlSG9zdCI6bnVsbH0&xcomponent=1&version=5.0.65&token=7J309736TV923131E#/checkout/genericError?code=UEFZRVJfQ0FOTk9UX1BBWQ%3D%3D

**Comment by wubuyun** [comment]
![2019-08-16 22-57-47屏幕截图](https://user-images.githubusercontent.com/35350235/63205337-59b32800-c079-11e9-8a5a-0b111eb10e0a.png)
