### ISSUE TITLE
"TypeError: Cannot read property 'Buttons' of undefined"

### ISSUE THREAD

**Issue by NicolasHofmairT23** [develodesign/vsf-payment-paypal#106]
Hi,
I want to include the Paypal Button at our page.
I followed the steps in your Readme for Frontend and Frontend-Api.

VS 1.10.0

The module gets registered, the Button itsfelf seems to have problems.
I did a yarn install and restarded the server (config ist working)
```
[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'Buttons' of undefined"
found in
---> <PaypalButton> at src/modules/paypal/components/Button.vue
```
This seems to be undefined `window.paypal`

```
window.paypal.Buttons({
      createOrder: this.createOrder,
      onApprove: this.onApprove
    }).render('.paypal-button')
```
Any ideas?

PS: I found this thread with a similar topic but the threadopener could solve the issue with yarn install and restart. https://forum.vuestorefront.io/t/paypal-payment-integration/152

**Comment by dimasch** [comment]
@NicolasHofmairT23 Hey,

Possible, the PayPal SDK not registered correctly, this point implemented by `beforeRegistration` hook. For more info:
https://github.com/develodesign/vsf-payment-paypal/blob/474610aab6cd8640cb5be7d23e77cdab5c6ef041/hooks/beforeRegistration.ts#L21

Need check this file `./src/modules/index.ts`, modules entrypoint.
```
...
import { Paypal } from './paypal'

export const registerModules: VueStorefrontModule[] = [
  ...,
  Paypal
]
```

**Comment by NicolasHofmairT23** [comment]
@dimasch Thank you for your response.

Registration of the Module was fine, it was actually the SDK Script.
I used a **wrong clientId**, after fixing this one, the Button appeared.
I could not see any error, that the SDK could not get loaded, so I missed checking this part.

Thanks for your answer!

**Comment by dimasch** [comment]
@NicolasHofmairT23  Thanks ! ;)
