### ISSUE TITLE
Cannot read property 'Buttons' of undefined"

### ISSUE THREAD

**Issue by ldc321** [develodesign/vsf-payment-paypal#111]
[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'Buttons' of undefined"
found in
---> <PaypalButton> at src/modules/paypal/components/Button.vue
       <OrderReview> at src/themes/default/components/core/blocks/Checkout/OrderReview.vue

TypeError: Cannot read property 'Buttons' of undefined
    at VueComponent.mounted (Button.vue:19)

**Comment by simonmaass** [comment]
i have the same problem

**Comment by simonmaass** [comment]
@ldc321 any help?
