### ISSUE TITLE
update_client_config_error

### ISSUE THREAD

**Issue by vineeth030** [develodesign/vsf-payment-paypal#117]
Hi, I\`m a beginner in Vue Storefront. I\`m trying to integrate Paypal to Vue Storefront. I have followed all steps in read me of this package. But I`m stuck following error for two days,

`update_client_config_error 
Uncaught TypeError: Cannot read property \'find\' of undefined at VueComponent.grandTotal (http://localhost:3000/dist/vsf-checkout.js:1446:25)`

Any idea how to fix this issue? Please help.

**Comment by dimasch** [comment]
@vineeth030 Vue Storefront core version ?

**Comment by vineeth030** [comment]
I somehow fixed this issue. Thank you responding.

**Comment by JaviCandia** [comment]
Hi @vineeth030 how you solved this?
