### ISSUE TITLE
Vue-storefront 1.10.5 is OK?

### ISSUE THREAD

**Issue by ldc321** [develodesign/vsf-payment-paypal#122]
It doesn't work!
![image](https://user-images.githubusercontent.com/57743360/78980435-7c3a0a00-7b50-11ea-9c89-40f82ddeea46.png)
Can't login Paypal!!!

**Comment by dimasch** [comment]
@ldc321 Thanks, for feedback. I will check.

**Comment by ldc321** [comment]
> @ ldc321感谢您的反馈。我会检查。

Is there a copy of the latest installation documentation! Thanks very much!This is my personal mailbox : cc_software@163.com

**Comment by ldc321** [comment]
> @ldc321 Thanks, for feedback. I will check.

Is there a copy of the latest installation documentation! Thanks very much!

**Comment by ldc321** [comment]
> @ldc321 Thanks, for feedback. I will check.

Is there a copy of the latest installation documentation! Thanks very much!

**Comment by dimasch** [comment]
This is fixed in #125, not related to VSF core compatibility.
And yes, order creation tested on v1.11.2 VSF core.

FYI. @ldc321 you can check to use v1.0.4 of this module.
