### ISSUE TITLE
Compatible with Capybara theme.

### ISSUE THREAD

**Issue by phongphanmage** [develodesign/vsf-payment-paypal#124]
Any updated documentation to make this module compatible to this theme: https://github.com/DivanteLtd/vsf-capybara

**Comment by dimasch** [comment]
@phongphanmage Yes, is possible. 
You can improve current documentation by pull request.
Will use atoms/molecules from Storefront UI.

Thanks.

**Comment by dimasch** [comment]
@phongphanmage Ready in `v1.1.0` release.
Thanks for idea.
