### ISSUE TITLE
Expected intent from order api call to be authorize, got capture

### ISSUE THREAD

**Issue by dimasch** [develodesign/vsf-payment-paypal#125]
`Expected intent from order api call to be authorize, got capture. Please ensure you are passing intent=capture to the sdk url.`

<img width="1218" alt="Снимок экрана 2020-06-11 в 17 00 34" src="https://user-images.githubusercontent.com/414067/84388353-7cfd2400-ac05-11ea-8815-14f454b5d104.png">

**Comment by konurbaev-e** [comment]
@dimasch could you please advise on how you solved the issue?

**Comment by dimasch** [comment]
@konurbaev-e 
By this commit: https://github.com/develodesign/vsf-payment-paypal/commit/0eadee7bb050401151fabe0b119131772c8f09bc#diff-039627b9ac58e411c11ebad5bcc1cab7c656a4ea804f8927c061775588c4c70f
