### ISSUE TITLE
Vsf 1.11.0

### ISSUE THREAD

**Issue by dearste** [develodesign/vsf-payment-paypal#128]
Hi, we use version 1.11.0, is this module compatible?

**Comment by dimasch** [comment]
@dearste  Yes, used on live site with VSF 1.11.2
Should be works.

Pls, to use compatibility section in `client.ts`

```
// Deprecated API, will be removed in 2.0
export const registerModules: VueStorefrontModule[] = [
  Paypal
]

```

**Comment by dearste** [comment]
Thanks!!
