### ISSUE TITLE
Cannot read property 'Buttons' of undefined"

### ISSUE THREAD

**Issue by ldc321** [develodesign/vsf-payment-paypal#129]
yes  i`m back!
vue-storefront is  v1.12.0  and  clientId is right , i get this error 
![image](https://user-images.githubusercontent.com/57743360/87918708-64f0ae00-caa9-11ea-88d4-c2712a803f7d.png)

**Comment by dimasch** [comment]
@ldc321 Now is ok?
help is needed?

**Comment by ldc321** [comment]
There is no problem.. Thank you very much


 
On 7/29/2020 13:49，Dmitry Schegolihin<notifications@github.com> wrote：

@ldc321 Now is ok?
help is needed?
