### ISSUE TITLE
Customers constantly have a mismatch in totals error when trying to use this module

### ISSUE THREAD

**Issue by webwolfcs** [develodesign/vsf-payment-paypal#144]
The totals of the cart item amounts do not match order amounts.

That's the error resulting in a failure to load the checkout. It works in incognito but it has not worked consistantly ever.

**Comment by dimasch** [comment]
@webwolfcs 
I think this is related improvements https://github.com/develodesign/vsf-payment-paypal/pull/143/files
Merged to master in prev time without tag. I will check again.

**Comment by rozzilla** [comment]
I confirm that this solves the issue! I had the exact problem on a live website, and I've solved it in this way.

**Comment by dimasch** [comment]
Thanks a lot, @rozzilla 

I will merge.
