### ISSUE TITLE
Magento 1.9.x support

### ISSUE THREAD

**Issue by Ogek** [develodesign/vsf-payment-paypal#146]
Hi folks!

I was wondering if this module could be used as well with Magento 1.9.x. 
As far I can see, the only code which refers to M2 is this: https://github.com/develodesign/vsf-payment-paypal/blob/master/components/PaypalButton.js#L36-L40.

Have you ever tried this module with M1? Or have you idea of which fields are required for M1?

**Comment by dimasch** [comment]
This is module compatible only with M2 version, you can check the main README.
https://github.com/develodesign/vsf-payment-paypal/blob/master/components/PaypalButton.js#L36-L40

**Comment by Ogek** [comment]
Ok but once the order has been saved on Magento I think it's basically done. Why we need to use NVP?

**Comment by dimasch** [comment]
> Why we need to use NVP?
Because for M2 this one works solution with invoice creation.

You can push pull request with support feature for M1.
@Ogek
