### ISSUE TITLE
Magento 1 integration

### ISSUE THREAD

**Issue by rozzilla** [develodesign/vsf-payment-paypal#149]
What steps do you recommend in order to integrate PayPal on VSF with Magento 1?

Thanks a lot

**Comment by rozzilla** [comment]
@dimasch, @collymore, any suggestion about that?

**Comment by rozzilla** [comment]
@dimasch I've tested this module and it works also with Magento 1.
You just need to manually [apply this fix](https://github.com/DivanteLtd/magento1-vsbridge/pull/55) to correctly create a PayPal order form VSF to Magento 1.

**Comment by dimasch** [comment]
Good news, thanks! @rozzilla
