### ISSUE TITLE
paypal  Error placing an order. PayPal gateway has rejected request. Shipping address is invalid (#10424: Transaction refused because of an invalid argument. See additional error messages for details).

### ISSUE THREAD

**Issue by ldc321** [develodesign/vsf-payment-paypal#157]
Error placing an order. PayPal gateway has rejected request. Shipping address is invalid (#10424: Transaction refused because of an invalid argument. See additional error messages for details).

country code: PH  Philippines

**Comment by ldc321** [comment]
Magneto was able to pay

**Comment by dimasch** [comment]
@ldc321 This is not a Paypal module related issue, the VSF this is platform for multiple backend connectors. And magento2 backend have specific related to the Region Code, if you send to m2 region name - you will see this message `Shipping address is invalid `

I will close.
