### ISSUE TITLE
Potential ssr memory leak

### ISSUE THREAD

**Issue by didkan** [develodesign/vsf-payment-paypal#159]
https://github.com/vuestorefront/vue-storefront/issues/5917
Bases on the above issue there is a potential server side memory leak here:
https://github.com/develodesign/vsf-payment-paypal/blob/956d5352b2f7963fdfd4543f1f3fbbb7d6b83814/hooks/afterRegistration.ts#L16-L22

**Comment by didkan** [comment]
Just noticed the `if (!isServer)` condition now, so this is probably not an actual issue.

Although VSF has deprecated the use of `Vue.prototype.$bus` so it should probably be fixed anyway.

**Comment by dimasch** [comment]
@didkan Thanks a lot!
