### ISSUE TITLE
Unable to get VSF Json config when module installed on custom theme.

### ISSUE THREAD

**Issue by naarnet** [develodesign/vsf-payment-paypal#50]
I installed a custom theme  when i am going to the checkout and i selected  the paypal payment method, the following error is returned when it gets a local configuration. can you help me please ?.

>Error in mounted hook: "TypeError: Cannot read property 'env' of undefined"
> <PaypalButton> at src/extensions/vsf-payment-paypal/components/Button.vue
 TypeError: Cannot read property 'env' of undefined 
 at VueComponent.configurePaypal (Button.vue:44)

> Button.vue:44   env: this.$config.paypal.env

**Comment by dimasch** [comment]
Hey! Txh for question. After added to config new section of paypal - need rebuild src:
By:
yarn build

**Comment by dimasch** [comment]
@naarnet Can i help you? You check after `yarn build` ?

**Comment by dimasch** [comment]
Migrated to new module structure. \+ @naarnet Pls, check.
