### ISSUE TITLE
Update beforeRegistration Hook Signatures for 1.8.0

### ISSUE THREAD

**Issue by tonyisworking** [develodesign/vsf-payment-paypal#75]
On VSF 1.8:
>Changed beforeRegistration and afterRegistration hooks signature. Now it contains only one object VSF. The subfields are the same as before so changing `beforeRegistration( Vue, config, store, isServer )` to `beforeRegistration({ Vue, config, store, isServer })`(and same with `afterRegistration`) is enough to make a proper migration to new API. - @filrak (#2330)

Need to update `beforeRegistration.ts` to be
```
export function beforeRegistration({ Vue, config, store, isServer }) {
```

Not sure if there's anything else to edit, but that stops VSF from complaining about it.

**Comment by dimasch** [comment]
Ok, thanks @tonyisworking !

**Comment by dimasch** [comment]
@tonyisworking Done.

**Comment by dimasch** [comment]
Have a good day!
