### ISSUE TITLE
PayPal transaction details are sent to Magento

### ISSUE THREAD

**Issue by ananth-iyer** [develodesign/vsf-payment-paypal#80]
I have tested and the order was placed successfully. 

But like Magento PayPal module, it saves transaction details like transaction id after placing an order. This plugin must be sent transaction details to Magento for future reference on the Admin side.

Like for refund an order that was paid through PayPal then where the admin can find the reference to the transaction.

Will it be possible to change the custom PayPal module?

**Comment by dimasch** [comment]
@ananth-iyer 
Thanks for request.

We plain to develop this feature. 

Create order with invoice`not paid yet` before send the customer to their bank site
After receive from payment gateway invoice status about ready payment - we update order status in m2 `not paid yet` => `payed`

https://docs.magento.com/m2/ce/user_guide/sales/invoice-create.html
https://webkul.com/blog/how-to-programmatically-create-invoice-in-magento2/

\+ @collymore

**Comment by dimasch** [comment]
https://webkul.com/blog/create-payment-transaction-in-magento2/

**Comment by tonyisworking** [comment]
@aureatelabs I forked and created a solution that uses the built in Paypal Module from 2.2.x and payment APIs [here](https://github.com/tonyisworking/vsf-payment-paypal/tree/feature/magento2-nvp). 

Basically It replicates the Paypal NVP method used by Magento2 and will use Magento2 Backend to Complete the Purchase then sends that confirmation back to the vsf api server to send back to the app.

It will send the transaction ID over to Magento using the built in processes without a need for any additional Magento Paypal Extensions, just the one that shipped with it. This should work til there is an Extension for the Restful apis.

**Comment by collymore** [comment]
@tonyisworking that sounds really good, thanks for your efforts and sharing. I'll take a look at this early next week and hopefully merge the work back in to this.

**Comment by tonyisworking** [comment]
@collymore Sounds good. I'll open a pull request.

**Comment by dimasch** [comment]
#118 Merged.
