### ISSUE TITLE
Deprecated PayPal integration

### ISSUE THREAD

**Issue by rain2o** [develodesign/vsf-payment-paypal#91]
According to PayPal the current integration method of using `checkout.js` is deprecated as of February 2019. See their notification here - https://developer.paypal.com/docs/archive/checkout/. 

It is recommended to build all new integrations with their PayPal Javascript SDK instead - https://developer.paypal.com/docs/checkout/. This would require a bit of rework, but should probably be considered sooner rather than later as there will be potentially quite a few more users of this module over time.

**Comment by dimasch** [comment]
<img width="755" alt="Снимок экрана 2019-07-30 в 0 04 53" src="https://user-images.githubusercontent.com/414067/62078535-e2e6f400-b25d-11e9-893b-26d06c86105a.png">

**Comment by dimasch** [comment]
@rain2o Ready. We migrated to new `Paypal Smart Buttons`.
Pls, check.

**Comment by rain2o** [comment]
Thanks @dimasch . We aren't actually using this module at the moment, we had to end up going with Braintree. But thanks for the fast reaction! Now this module will be up-to-date with PayPal's recommendations.
