### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wubuyun** [develodesign/vsf-payment-paypal#99]
![2019-08-12 01-22-41屏幕截图](https://user-images.githubusercontent.com/35350235/62845620-f2276200-bc9f-11e9-9a71-b2eedcba81f6.png)
![2019-08-12 01-23-15屏幕截图](https://user-images.githubusercontent.com/35350235/62845621-f2276200-bc9f-11e9-8579-2b6a0ac40b2f.png)
![2019-08-12 01-23-49屏幕截图](https://user-images.githubusercontent.com/35350235/62845622-f2276200-bc9f-11e9-9bc1-1cc21455f826.png)

**Comment by dimasch** [comment]
@wubuyun Need more info. 
Which version of VSF are you using ?

**Comment by wubuyun** [comment]
New version 1.10.0

**Comment by dimasch** [comment]
@wubuyun Thanks, in `1.10.0` 
`The getter cart/totals has ben replaced with cart/getTotals - @pkarw (#2522)`
https://github.com/DivanteLtd/vue-storefront/releases

**Comment by dimasch** [comment]
@wubuyun Fixed in `v0.6.0`
